name: Destroy
on:
  workflow_dispatch:
  push:
    branches:
      - destroy
    paths:
      - 'docker-compose.yml'
      - 'Makefile'
      - '.github/workflows/**'
      - '*dockerfile'
      - 'modules/**'
      - '**.tf'

jobs:
  terraform_destroy_plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
      SLACK_WEBHOOK:  ${{ secrets.SLACK_WEBHOOK }} 
    steps:
    - uses: actions/checkout@v2
    - name: Notify_Slack
      run: ./scripts/slack_notify.sh "Destroying Infrastructure"
    - name: Terraform_Destroy_Plan
      run: make run_destroy_plan       

  terraform_destroy_apply:
    environment:
      name: approval
    needs: terraform_destroy_plan
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
      SLACK_WEBHOOK:  ${{ secrets.SLACK_WEBHOOK }} 
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Destroy_Apply
      run: make run_destroy_apply 
    - name: Notify_Slack
      run: ./scripts/slack_notify.sh "Project destroyed successfully"
